version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: moderation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    env_file:
      - .env

  submit_bot:
    build:
      context: .
      dockerfile: Dockerfile.moderation
    command: python -m bots.moderation_bot
    container_name: moderation_bot
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

volumes:
  redis_data: